lang: en
title: a blog on software engineering topics
author: ""
url: "https://cristian.regolo.cc"
baseurl: ""
description: a blog on software engineering topics
theme: minima
show_excerpts: true
google_site_verification: googlea12deda5da4bc2bf
google_analytics: UA-65079873-1
permalink: /:year/:month/:day/:title.html
twitter_username: cristiangreco
github_username:  cristiangreco
linkedin_username: cristiangreco
social:
  name: Cristian Greco
disqus:
  shortname: cristianregolocc
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
